### ISSUE TITLE
Page number beyond the bottom of the page

### ISSUE THREAD

**Issue by StableAgOH** [Tiphereth-A/TINplate#2]
OS: Ubuntu 22.04
Python: 3.10.4
LaTeX: TeX Live 2022

The compiled PDF is like the following:

![image](https://user-images.githubusercontent.com/50107074/168473138-644e1018-e15e-4925-9efd-763f4dc165df.png)

**Comment by Tiphereth-A** [comment]
Hi, this bug should have been fixed in the latest commit
